name: test Image using pi-gen
run-name: test Homebridge Image ${{ github.event.inputs.version }} against ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version / Tag (vx.x.x):'     
        required: true

env:
  devices: '["pi5-32bit", "pi4-32bit", "pi3-32bit", "pi2-32bit", "pi1-32bit"]'

jobs:
  setup_environment:
    name: Setup Environment ${{ github.event.inputs.version }}
    runs-on: [ubuntu-latest] 
    steps:

    - uses: actions/checkout@v4
    - name: Generate rpi-image-repo.json 
      id: generate_rpi-image-repo
      run: |
        export RPI_IMAGER_NAME="Homebridge ${{ matrix.release }} (${{ matrix.name }})"
        export RPI_IMAGER_DESCRIPTION="Official Homebridge Raspberry Pi Image ${{ matrix.release }} (${{ matrix.name }})"
        export RPI_IMAGER_ICON="https://user-images.githubusercontent.com/3979615/116509191-3c35f880-a906-11eb-9a7f-7cad7c2aa641.png"
        export RPI_IMAGER_WEBSITE="https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started"
        export RPI_IMAGER_IMAGE_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.version }}/${{ env.IMGFILENAME }}"
        export RPI_IMAGER_DEVICES='${{ env.devices }}'
        ./make_rpi-imager-snipplet.py --rpi_imager_url ${RPI_IMAGER_IMAGE_URL}
